module.exports = {
  apps: [
    {
      name: 'cara',
      script: 'serve',
      cwd: '/home/enflujo/enflujo-fax',
      env: {
        PM2_SERVE_PATH: '/home/enflujo/enflujo-fax/aplicaciones/cara/publico',
        PM2_SERVE_PORT: 4001,
        PM2_SERVE_SPA: 'true',
      },
      exec_mode: 'fork',
      autorestart: true,
      restart_delay: 2000,
      max_memory_restart: '300M',
      out_file: '/home/enflujo/.pm2/logs/cara-out.log',
      error_file: '/home/enflujo/.pm2/logs/cara-err.log',
      interpreter: '/home/enflujo/.nvm/versions/node/v24.11.1/bin/node',
    },
    {
      name: 'culo',
      script: '/home/enflujo/enflujo-fax/aplicaciones/culo/publico/culito.js',
      cwd: '/home/enflujo/enflujo-fax/aplicaciones/culo',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      restart_delay: 2000,
      max_memory_restart: '300M',
      env: { NODE_ENV: 'production' },
      out_file: '/home/enflujo/.pm2/logs/culo-out.log',
      error_file: '/home/enflujo/.pm2/logs/culo-err.log',
      interpreter: '/home/enflujo/.nvm/versions/node/v24.11.1/bin/node',
    },
  ],
};
