name: Estilo Código

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: 🐯 Obtener código del repositorio
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: 🐝 Usar Node
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: 🧶 Activar Yarn
        run: corepack enable

      - name: 🦒 Instalar dependencias
        run: yarn install --immutable

      - name: 👀 Buscar errores
        run: yarn revisar

      - name: 🧱 Comprobar compilación
        run: yarn armar
